export const titleTower = 'Выбор Башни *'
export const titleFloor = 'Выбор Этажа *'
export const titleMeeting = 'Выбор Переговорной комнаты *'
export const titleStart = 'Выбор Начала времени *'
export const titleEnd = 'Выбор Конца времени *'
export const defaultText = 'Не выбрано'
